CLUSTAL multiple sequence alignment by MUSCLE (3.8)


(gamma_conotoxin)_PnVIIA              -----------------DC-----TSWFGRC-------TVNSE---C------CSNS--C
(delta_conotoxin)_Evia_Loop_2_An      -------------------------GFASLX---------------I------LKNG---
(alpha_conotoxin)_SII                 ----------------GCC-----------C-------NPA-----CGPNYG-CGTS---
(alpha_conotoxin)_SI                  -----------------IC-----------C-------NPACGPKYS------C------
(mu_conotoxin)_SxIIIA                 ----------------RCC-----TGKKGSC-----S-GRA-----C------KNLK--C
(mu_conotoxin)_SxIIIB                 ---------------QKCC-----TGKKGSC-----S-GRA-----C------KNLR--C
(mu_conotoxin)_CIIIA                  ---------------GRCC------EGPNGC-----S-SRW-----C------KDHAR-C
(mu_conotoxin)_KIIIA[Del1,S3/S4A      ------------------C----------NC-------NKW-----A------RDHAR-C
(mu_conotoxin)_SIIIB                  ---------------QNCC--------NGGC-----S-SKW-----C------KGHAR-C
(mu_conotoxin)_CnIIIC                 ----------------QGC-----CNGPKGC-----S-SKW-----C------RDHAR-C
(mu_conotoxin)_SIIIA                  ---------------QNCC--------NGGC-----S-SKW-----C------RDHAR-C
(mu_conotoxin)_KIIIA[C2A,C15A]        ------------------C---------ANC-----S-SKW-----C------RDHS-RA
(mu_conotoxin)_KIIIA[C4A,C16A]        -----------------CC-----NASSKWC----------------------RDHS--R
(mu_conotoxin)_KIIIA[C1A,C9A]         -----------------AC----------NC-----S-SKW-----A------RDHS-RC
(mu_conotoxin)_SmIIIA                 ---------------QRCC------NGRRGC-----S-SRW-----C------RDHS-RC
(mu_conotoxin)_KIIIA                  -----------------CC----------NC-----S-SKW-----C------RDHSR-C
(mu_conotoxin)_MIIIA                  ----------------QGC-----CNVPNGC-----S-GRW-----C------RDHAQ-C
(mu_conotoxin)_CnIIIA                 ---------------GRCC------DVPNAC-----S-GRW-----C------RDHAQ-C
(kappa_conotoxin)_PlXIVA              ------------------------FPRPRIC-------NL------A------CRAGIGH
(gamma_conotoxin)_DeVIIA              -----------------AC-----KPKNNLC-----A-ITEMAE--C------CSGF--C
(alpha_conotoxin)_RVIIIA              ------------KCNFDKCKGTGVYNCGESC-----SCEGLHS---CR-----CTYNIGS
(omega_conotoxin)_SO4                 ---------------ATDC-----IEAGNYC-----G-PTVMK---I------CCGF--C
(omega_conotoxin)_SO5                 ---------------STSC-----MEAGSYC-----G-STTRI----------CCGY--C
(omega_conotoxin)_PuIIA               -----------------TC-----NTPTQYC-----T-LHRH----C------CSLY--C
(mu_conotoxin)_CnIIIB                 ----------------QGC-----------C-----G-EPNLCFTRW------CRNNARC
(gamma_conotoxin)_TxVIIA              ------------------C-----GGYSTYC-------EVDSE---C------CSDN--C
(alpha_conotoxin)_PIIIE               --------------HPPCC-----LYGK--C----RR-YP------G------CSSAS-C
(mu_conotoxin)_TIIIA                  ---------------RHGC-----------C-----K-GPKG----C------SSRE--C
(alpha_conotoxin)_SrIA                ----------------RTC-----------C-----S-RP------T------CRME--Y
(omega_conotoxin)_TxO2                ------------------C-----YDSGTSC---NTG-NQ------C------CSGW--C
(omega_conotoxin)_TxO3                ------------------C-----YDGGTSC---DSG-IQ------C------CSGW--C
(chi_conotoxin)_CMrX                  -----------------GI-----------C----------------------CGVSF-C
(alpha_conotoxin)_Qc1.2               -----------------QC-----------C-----A-NP------P------CKHV--N
(mu_conotoxin)_LtVIC                  ----------------WPC-----KVAGSPC-----G-LVSECCGTCNVLRNRC------
(kappa_conotoxin)_RIIIK               --------------LPSCC-----SLNLRLC-----P-VP------A------CKRNP-C
(mu_conotoxin)_PIIIA                  ---------------QRLC-----------C-----G-FPKSCRSRQ------CKPHR-C
(kappa_conotoxin)_MIVA                ------APELVVTATTNCC----GYNPMTIC-------PP-------------CMCTY-S
(kappa_conotoxin)_SIVA                ------QKSLVPSVITTCC----GYDPGTMC-------PP-------------CRCTN-S
(omega_conotoxin)_SVIA                ------------------C-----RSSGSPC-----G-VTSICCGRCYRGK--CT-----
(omega_conotoxin)_SVIA_mutant_1       ------------------C-----RPSGSPC-----G-VTSICCGRCYRGK--CT-----
(chi_conotoxin)_Cyclic_MrIA           --------------NGVCC-------GYKLC-------HP-------------CAG----
(chi_conotoxin)_MrIA                  --------------NGVCC-------GYKLC-------HP-------------C------
(chi_conotoxin)_CMrVIA_amidated       ----------------VCC-------GYKLC-------HP-------------C------
(chi_conotoxin)_MrIB_C-term_amid      --------------VGVCC-------GYKLC-------HP-------------C------
(chi_conotoxin)_MrIB                  --------------VGVCC-------GYKLC-------HP-------------C------
(chi_conotoxin)_CMrVIA                ----------------VCC-------GYKLC-------HP-------------C------
(chi_conotoxin)_CMrVIA_[K6P]          ----------------VCC-------GYPLC-------HP-------------C------
(chi_conotoxin)_CMrVIA_[K6P]_ami      ----------------VCC-------GYPLC-------HP-------------C------
(alpha_conotoxin)_Lp1.1               -----------------GC-----------C-----A-RA------A------CAGI--H
(delta_conotoxin)_CnVIA               ----------------YEC-----YSTGTFC-----G-INGGL---C------CSNL--C
(delta_conotoxin)_NgVIA               ----------------SKC-----FSPGTFC-----G-IKPGL---C------CSVR--C
(delta_conotoxin)_MVID                ----------------EAC-----YNAGTFC-----G-IKPGL---C------CSAI--C
(delta_conotoxin)_MVIC                ----------------DEC-----YPPGTFC-----G-IKPGL---C------CSAI--C
(delta_conotoxin)_EVIB                ----------------EAC-----YPPGTFC-----G-IKPGL---C------CSEL--C
(delta_conotoxin)_PVIA                ----------------EAC-----YAPGTFC-----G-IKPGL---C------CSEF--C
(delta_conotoxin)_EVIA                ----------------DDC-----IKXYGFC-----S-LPILKNGLC------CSGA--C
(omega_conotoxin)_PnVIA               -----------------GC-----LEVDYFC-----G-IPFANNGLC------CSGN--C
(alpha_conotoxin)_PIB                 --------------QSPGC-----------C-----W-NP------A------CVKN--R
(omega_conotoxin)_PnVIB               ---------------DDDC-----EPPGNFCGMIKIG-PP------C------CSGW--C
(omega_conotoxin)_TxO4                ----------------YDC-----EPPGNFCGMIKIG-PP------C------CSGW--C
(delta_conotoxin)_BVIA                ----------------DEC-----SAPGAFC-----L-IRPGL---C------CSEF--C
(delta_conotoxin)_CVIE                ----------------YGC-----SNAGAFC-----G-IHPGL---C------CSEL--C
(delta_conotoxin)_AVIA                ----------------DGC-----SNAGAFC-----G-IHPGL---C------CSEI--C
(delta_conotoxin)_MVIB                ----------------EAC-----YNAGSFC-----G-IHPGL---C------CSEF--C
(delta_conotoxin)_MVIA                ----------------DGC-----YNAGTFC-----G-IRPGL---C------CSEF--C
(delta_conotoxin)_SmVIA               ----------------DGC-----SSGGTFC-----G-IRPGL---C------CSEF--C
(delta_conotoxin)_SVIE                ----------------DGC-----SSGGTFC-----G-IHPGL---C------CSEF--C
(omega_conotoxin)_PuIA                ----------------RDC-----RPVGQYC-----G-IPYEHNWRC------CSQL--C
(alpha_conotoxin)_MII_[N5Ada]         -----------------GC-----------C-----S-XP------V------CHLE--H
(alpha_conotoxin)_MII_[E11A]          -----------------GC-----------C-----S-NP------V------CHLA--H
(alpha_conotoxin)_MII                 -----------------GC-----------C-----S-NP------V------CHLE--H
(alpha_conotoxin)_MII-7               -----------------GC-----------C-----S-NP------V------CHLE--H
(alpha_conotoxin)_MII-6               -----------------GC-----------C-----S-NP------V------CHLE--H
(alpha_conotoxin)_Ada-MII             ----------------XGC-----------C-----S-NP------V------CHLE--H
(alpha_conotoxin)_ImII                -----------------AC-----------C-----S-DR------R------CRWR---
(alpha_conotoxin)_ImII-iso            -----------------AC-----------C-----S-DR------R------CRWR---
(alpha_conotoxin)_ImII_[W10Y]         -----------------AC-----------C-----S-DR------R------CRYR---
(alpha_conotoxin)_Epi_[sTy15>Y]       -----------------GC-----------C-----S-DP------R------CNMN--N
(alpha_conotoxin)_EpI                 -----------------GC-----------C-----S-DP------R------CNMN--N
(alpha_conotoxin)_Vc1.1[N9D]          -----------------GC-----------C-----S-DP------R------CDYD--H
(alpha_conotoxin)_Vc1.1[N9L]          -----------------GC-----------C-----S-DP------R------CLYD--H
(alpha_conotoxin)_Vc1.1[N9I]          -----------------GC-----------C-----S-DP------R------CIYD--H
(alpha_conotoxin)_Vc1.1[N9K]          -----------------GC-----------C-----S-DP------R------CKYD--H
(alpha_conotoxin)_Vc1.1[N9G]          -----------------GC-----------C-----S-DP------R------CGYD--H
(alpha_conotoxin)_Vc1.1[S4K,N9A]      -----------------GC-----------C-----K-DP------R------CAYD--H
(alpha_conotoxin)_Vc1.1[N9A]          -----------------GC-----------C-----S-DP------R------CAYD--H
(alpha_conotoxin)_Vc1.1[I15D]         -----------------GC-----------C-----S-DP------R------CNYD--H
(alpha_conotoxin)_Vc1.1[I15K]         -----------------GC-----------C-----S-DP------R------CNYD--H
(alpha_conotoxin)_Vc1.1[I15A]         -----------------GC-----------C-----S-DP------R------CNYD--H
(alpha_conotoxin)_Vc1.1[E14K]         -----------------GC-----------C-----S-DP------R------CNYD--H
(alpha_conotoxin)_Vc1.1[E14A]         -----------------GC-----------C-----S-DP------R------CNYD--H
(alpha_conotoxin)_Vc1.1[E14D]         -----------------GC-----------C-----S-DP------R------CNYD--H
(alpha_conotoxin)_Vc1.1[S4D]          -----------------GC-----------C-----D-DP------R------CNYD--H
(alpha_conotoxin)_Vc1.1[S4K]          -----------------GC-----------C-----K-DP------R------CNYD--H
(alpha_conotoxin)_Vc1.1[S4R]          -----------------GC-----------C-----R-DP------R------CNYD--H
(alpha_conotoxin)_Vc1.1[S4A]          -----------------GC-----------C-----A-DP------R------CNYD--H
(alpha_conotoxin)_Vc1.1[D5K]          -----------------GC-----------C-----S-KP------R------CNYD--H
(alpha_conotoxin)_Vc1.1[D5A]          -----------------GC-----------C-----S-AP------R------CNYD--H
(alpha_conotoxin)_Vc1.1[P13D]         -----------------GC-----------C-----S-DP------R------CNYD--H
(alpha_conotoxin)_Vc1.1[P13K]         -----------------GC-----------C-----S-DP------R------CNYD--H
(alpha_conotoxin)_Vc1.1[P13A]         -----------------GC-----------C-----S-DP------R------CNYD--H
(alpha_conotoxin)_Vc1.1[D11K]         -----------------GC-----------C-----S-DP------R------CNYK--H
(alpha_conotoxin)_Vc1.1[D11A]         -----------------GC-----------C-----S-DP------R------CNYA--H
(alpha_conotoxin)_Vc1.1[P6D]          -----------------GC-----------C-----S-DD------R------CNYD--H
(alpha_conotoxin)_Vc1.1[P6K]          -----------------GC-----------C-----S-DK------R------CNYD--H
(alpha_conotoxin)_Vc1.1[P6A]          -----------------GC-----------C-----S-DA------R------CNYD--H
(alpha_conotoxin)_Vc1.1[R7D]          -----------------GC-----------C-----S-DP------D------CNYD--H
(alpha_conotoxin)_Vc1.1[R7A]          -----------------GC-----------C-----S-DP------A------CNYD--H
(alpha_conotoxin)_Vc1.1[R7K]          -----------------GC-----------C-----S-DP------K------CNYD--H
(alpha_conotoxin)_Vc1.1[Y10D]         -----------------GC-----------C-----S-DP------R------CNDD--H
(alpha_conotoxin)_Vc1.1[Y10K]         -----------------GC-----------C-----S-DP------R------CNKD--H
(alpha_conotoxin)_Vc1.1[Y10A]         -----------------GC-----------C-----S-DP------R------CNAD--H
(alpha_conotoxin)_Vc1.1[G1D]          -----------------DC-----------C-----S-DP------R------CNYD--H
(alpha_conotoxin)_Vc1.1[G1K]          -----------------KC-----------C-----S-DP------R------CNYD--H
(alpha_conotoxin)_Vc1.1[G1A]          -----------------AC-----------C-----S-DP------R------CNYD--H
(alpha_conotoxin)_Vc1.1[H12D]         -----------------GC-----------C-----S-DP------R------CNYD--D
(alpha_conotoxin)_Vc1.1[H12A]         -----------------GC-----------C-----S-DP------R------CNYD--A
(alpha_conotoxin)_Vc1.1               -----------------GC-----------C-----S-DP------R------CNYD--H
(alpha_conotoxin)_Vc1.1[H12K]         -----------------GC-----------C-----S-DP------R------CNYD--K
(alpha_conotoxin)_Reg1e               -----------------GC-----------C-----S-DP------R------CRYR---
(alpha_conotoxin)_RgIA                -----------------GC-----------C-----S-DP------R------CRYR---
(alpha_conotoxin)_Reg1b/Reg1c         -----------------GC-----------C-----S-DP------R------CKHQ---
(alpha_conotoxin)_Reg1d               -----------------GC-----------C-----S-DP------R------CKHE---
(alpha_conotoxin)_ImI_[P6A]           -----------------GC-----------C-----S-DA------R------CAWR---
(alpha_conotoxin)_ImI_[P6K]           -----------------GC-----------C-----S-DK------R------CAWR---
(alpha_conotoxin)_ImI_[P6K]_deam      -----------------GC-----------C-----S-DK------R------CAWR---
(alpha_conotoxin)_ImI_[R11E]          -----------------GC-----------C-----S-DP------R------CAWE---
(alpha_conotoxin)_ImI_[D5N]           -----------------GC-----------C-----S-NP------R------CAWR---
(alpha_conotoxin)_ImI_[R7L]           -----------------GC-----------C-----S-DP------L------CAWR---
(alpha_conotoxin)_ImI                 -----------------GC-----------C-----S-DP------R------CAWR---
(alpha_conotoxin)_ImI_[C2U,C8U]       -----------------GC-----------C-----S-DP------R------CAWR---
(alpha_conotoxin)_ImI_[C2U,C3U,C      -----------------GC-----------C-----S-DP------R------CAWR---
(alpha_conotoxin)_ImI_deamidated      -----------------GC-----------C-----S-DP------R------CAWR---
(alpha_conotoxin)_ArIB_[N6R,A8P]      ----------------DEC-----------C-----S-RP------P------CRVN--N
(alpha_conotoxin)_ArIB_[V1            ----------------DEC-----------C-----S-NP------A------CRLN--N
(alpha_conotoxin)_ArIB_[V11L]         ----------------DEC-----------C-----S-NP------A------CRLN--N
(alpha_conotoxin)_ArIB_[V2            ----------------DEC-----------C-----S-NP------A------CRLN--N
(alpha_conotoxin)_GID*[V18A]          --------------IRDEC-----------C-----S-NP------A------CRVN--N
(alpha_conotoxin)_GID*[O16A]          --------------IRDEC-----------C-----S-NP------A------CRVN--N
(alpha_conotoxin)_GID*[P9A]           --------------IRDEC-----------C-----S-NA------A------CRVN--N
(alpha_conotoxin)_GID*[S7A]           --------------IRDEC-----------C-----A-NP------A------CRVN--N
(alpha_conotoxin)_GID*[H17A]          --------------IRDEC-----------C-----S-NP------A------CRVN--N
(alpha_conotoxin)_GID*[N15A]          --------------IRDEC-----------C-----S-NP------A------CRVN--A
(alpha_conotoxin)_GID*[N8A]           --------------IRDEC-----------C-----S-AP------A------CRVN--N
(alpha_conotoxin)_GID*[V13A]          --------------IRDEC-----------C-----S-NP------A------CRAN--N
(alpha_conotoxin)_GID*[N14A]          --------------IRDEC-----------C-----S-NP------A------CRVA--N
(alpha_conotoxin)_GID[R12A]           --------------IRDXC-----------C-----S-NP------A------CRVN--N
(alpha_conotoxin)_GID[Gla4Ala]        --------------IRDAC-----------C-----S-NP------A------CRVN--N
(alpha_conotoxin)_GID[Del1-3,Gla      -----------------AC-----------C-----S-NP------A------CRVN--N
(alpha_conotoxin)_GID[Del4]           ------------------C-----------C-----S-NP------A------CRVN--N
(alpha_conotoxin)_GID*[D3A]           --------------IRAEC-----------C-----S-NP------A------CRVN--N
(alpha_conotoxin)_GID*[Del1-2,D3      ----------------AEC-----------C-----S-NP------A------CRVN--N
(alpha_conotoxin)_GID*[Del1-3]        -----------------EC-----------C-----S-NP------A------CRVN--N
(alpha_conotoxin)_GID*-NH2            --------------IRDEC-----------C-----S-NP------A------CRVN--N
(alpha_conotoxin)_GID                 --------------IRDEC-----------C-----S-NP------A------CRVN--N
(alpha_conotoxin)_GID*                --------------IRDEC-----------C-----S-NP------A------CRVN--N
(alpha_conotoxin)_GID*[O16P]          --------------IRDEC-----------C-----S-NP------A------CRVN--N
(alpha_conotoxin)_GID*[Del1,R2A]      ---------------ADEC-----------C-----S-NP------A------CRVN--N
(alpha_conotoxin)_GID*[R2A]           --------------IADEC-----------C-----S-NP------A------CRVN--N
(alpha_conotoxin)_ArIA                --------------IRDEC-----------C-----S-NP------A------CRVN--N
(alpha_conotoxin)_GID*[I1A]           --------------ARDEC-----------C-----S-NP------A------CRVN--N
(alpha_conotoxin)_ArIB                ----------------DEC-----------C-----S-NP------A------CRVN--N
(alpha_conotoxin)_PeIA                -----------------GC-----------C-----S-HP------A------CSVN--H
(alpha_conotoxin)_BuIA                -----------------GC-----------C-----S-TP------P------CAVL--Y
(alpha_conotoxin)_OmIA                -----------------GC-----------C-----S-HP------A------CNVN--N
(alpha_conotoxin)_RegIIA              -----------------GC-----------C-----S-HP------A------CNVN--N
(alpha_conotoxin)_GIC                 -----------------GC-----------C-----S-HP------A------CAGN--N
(alpha_conotoxin)_AnIB                ----------------GGC-----------C-----S-HP------A------CAAN--N
(alpha_conotoxin)_AnIA                ------------------C-----------C-----S-HP------A------CAAN--N
(alpha_conotoxin)_AuIB                -----------------GC-----------C-----S-YP------P------CFAT--N
(alpha_conotoxin)_AuIC                -----------------GC-----------C-----S-YP------P------CFAT--N
(alpha_conotoxin)_AuIA                -----------------GC-----------C-----S-YP------P------CFAT--N
(alpha_conotoxin)_TxIA                -----------------GC-----------C-----S-RP------P------CIAN--N
(alpha_conotoxin)_PnIA_[A10L,D14      -----------------GC-----------C-----S-LP------P------CALN--N
(alpha_conotoxin)_PnIA                -----------------GC-----------C-----S-LP------P------CAAN--N
(alpha_conotoxin)_Pni1                -----------------GC-----------C-----S-LP------P------CAAN--N
(alpha_conotoxin)_PnIB                -----------------GC-----------C-----S-LP------P------CALS--N
(alpha_conotoxin)_Reg1f               ----------------DYC-----------C-----R-RP------P------CTL----
(alpha_conotoxin)_EI                  ---------------RDPC-----------C-----Y-HP------T------CNMS--N
(alpha_conotoxin)_PIA                 ---------------RDPC-----------C-----S-NP------V------CTVH--N
(alpha_conotoxin)_VxXXC               -DLRQCTRNAPGSTWGRCC-------LNPMC-----G-NF------C------CPRSG-C
(alpha_conotoxin)_VxXXB               DDESECIINTRDSPWGRCC-------RTRMC-----G-SM------C------CPRNG-C
(alpha_conotoxin)_VxXXA               --------------DVQDCQVSTPGSKWGRC-----C-LNRVCGPMC------CPASHCY
(mu_conotoxin)_conotoxin-GS           -----------------AC-----SGRGSRC-------PPQ-----C------CMGLR-C
(kappa_conotoxin)_PIVF                ----------------DCC-----GVKLEMC-------HP------C------LCDN--S
(kappa_conotoxin)_PIVE                ----------------DCC-----GVKLEMC-------HP------C------LCDN--S
(alpha_conotoxin)_GI_[S12>Benzoy      -----------------EC-----------C-------NPA-----C------GRHY--X
(alpha_conotoxin)_GI                  -----------------EC-----------C-------NPA-----C------GRHY--S
(alpha_conotoxin)_GIA                 -----------------EC-----------C-------NPA-----C------GRHY--S
(alpha_conotoxin)_GI_[N4>Benzoyl      -----------------EC-----------C-------XPA-----C------GRHY--S
(alpha_conotoxin)_SIA                 -----------------YC-----------C-------HPA-----C------GKNF--D
(alpha_conotoxin)_CnIA                ----------------GRC-----------C-------HPA-----C------GKYY--S
(alpha_conotoxin)_MI                  ----------------GRC-----------C-------HPA-----C------GKNY--S
(alpha_conotoxin)_Ac1.1a              ---------------NGRC-----------C-------HPA-----C------GKHF--N
(alpha_conotoxin)_GII                 -----------------EC-----------C-------HPA-----C------GKHF--S
(kappa_conotoxin)_BtX                 ------------------C-----RAEGTYC-----E-NDSQC---C------LNEC--C
(delta_conotoxin)_GmVIA               ---------------VKPC-----RKEGQLC-------DPIFQN--C------CRGWN-C
(omega_conotoxin)_TxVII               ------------------C-----KQADEPC-----D-VFSLD---C------CTGI--C
(omega_conotoxin)_TxO1                ------------------C-----LDAGEVC-----D-IFFPT---C------CGY---C
(delta_conotoxin)_Am2766              ------------------C-----KQAGESC-----D-IFSQN---C------CVGT--C
(alpha_conotoxin)_PrIIIE              ---------------AARC-----------C-------TYHGS---C------LKEK--C
(omega_conotoxin)_TxO6                ----------------NYC-----QEKWDYC-----P-VPFLGSRYC------CDGLF-C
(omega_conotoxin)_TxO5                ------------------C-----VPYEGPC-----N-WLTQN---C------CDAT--C
(mu_conotoxin)_MrVIA                  -----------------AC-----RKKWEYC-----I-VPIIGFIYC------CPGLI-C
(mu_conotoxin)_MrVIB                  -----------------AC-----SKKWEYC-----I-VPILGFVYC------CPGLI-C
(alpha_conotoxin)_PIIIF               ---------------------------GPPC---------------CLYGS--CRPFPGC
(delta_conotoxin)_TxVIA               -----------------WC-----KQSGEMC-----N-LLDQN---C------CDGY--C
(delta_conotoxin)_TxVIB               -----------------WC-----KQSGEMC-----N-VLDQN---C------CDGY--C
(mu_conotoxin)_PnIVB                  ------------------C-----------C-------KYGWT---C------WLGCSPC
(mu_conotoxin)_PnIVA                  ------------------C-----------C-------KYGWT---C------LLGCSPC
(alpha_conotoxin)_PIVA                -----------------GC-----------C-----G-SYPNA---A------CHPCS-C
(alpha_conotoxin)_PIVA_[Hyp7P,Hy      -----------------GC-----------C-----G-SYPNA---A------CHPCS-C
(alpha_conotoxin)_EIVA                -----------------GC-----------C-----GPYPNAA----------CHPCG-C
(alpha_conotoxin)_EIVB                -----------------GC-----------C-----GKYPNAA----------CHPCG-C
(alpha_conotoxin)_OIVB                ------------------C-----------C-----G-VPNAA----------CPPCV-C
(alpha_conotoxin)_OIVA                ------------------C-----------C-----G-VPNAA----------CHPCV-C
(alpha_conotoxin)_PeIVB               ------------------C-----------C-----G-IPNAA----------CHPCV-C
(alpha_conotoxin)_PeIVA               ------------------C-----------C-----G-VPNAA----------CHPCV-C
(kappa_conotoxin)_PVIIA               ------------------C-----RIPNQKC-----F-QHLDD---C------CSRK--C
(omega_conotoxin)_TVIA                ------------------C-----LSPGSSC-----S-PTSYN---C------CRS---C
(omega_conotoxin)_GVIA_[O10>K]        ------------------C-----KSNGSSC-----S-KTSYN---C------CRS---C
(omega_conotoxin)_GVIA                ------------------C-----KSPGSSC-----S-PTSYN---C------CRS---C
(gamma_conotoxin)_AsVIIA              -----------------TC-----KQKGEGC-----S--LDVE---C------CSSS--C
(omega_conotoxin)_GVIIA               ------------------C-----KSPGTPC-----S-RGMRD---C------CTS---C
(omega_conotoxin)_GVIIB               ------------------C-----KSPGTPC-----S-RGMRD---C------CTS---C
(mu_conotoxin)_GIIIA_[R13A]           ----------------RDC----------------------------------CTPPKKC
(mu_conotoxin)_GIIIA                  ----------------RDC----------------------------------CTPPKKC
(mu_conotoxin)_GIIIB                  ----------------RDC----------------------------------CTPPRKC
(mu_conotoxin)_GIIIC                  ----------------RDC----------------------------------CTPPKKC
(omega_conotoxin)_RVIA                ------------------C-----KPPGSPC-----R-VSSYN---C------CSS---C
(alpha_conotoxin)_LtXIVA              ----------------------------------------------M------CPPL--C
(mu_conotoxin)_LtVd                   -----------------DC----------------------------------CPAKLLC
(omega_conotoxin)_SO3                 ------------------C-----KAAGKPC-----S-RIAYN---C------CTGS--C
(omega_conotoxin)_MVIID               ------------------C-----QGRGASC-----R-KTMYN---C------CSGS--C
(omega_conotoxin)_MVIIB               ------------------C-----KGKGASC-----H-RTSYD---C------CTGS--C
(omega_conotoxin)_CVIA                ------------------C-----KSTGASC-----R-RTSYD---C------CTGS--C
(omega_conotoxin)_CVID                ------------------C-----KSKGAKC-----S-KLMYD---C------CSGS--C
(omega_conotoxin)_CnVIIA              ------------------C-----KGKGAPC-----T-RLMYD---C------CHGS--C
(omega_conotoxin)_SVIB                ------------------C-----KLKGQSC-----R-KTSYD---C------CSGS--C
(omega_conotoxin)_SNX-202             ------------------C-----KLKGQSC-----S-RLMYD---C------CSGS--C
(omega_conotoxin)_MVIIC               ------------------C-----KGKGAPC-----R-KTMYD---C------CSGS--C
(omega_conotoxin)_MVIIC_analog        ------------------C-----KGKGAPC-----R-KTMYD---C------CKGR--C
(omega_conotoxin)_CVIB                ------------------C-----KGKGASC-----R-KTMYD---C------CRGS--C
(omega_conotoxin)_SNX-201             ------------------C-----KGKGAKC-----R-KTSYD---C------CTGS--C
(omega_conotoxin)_CVIC                ------------------C-----KGKGQSC-----S-KLMYD---C------CTGS--C
(omega_conotoxin)_SNX-273             ------------------C-----KGKGAKC-----S-RLAYD---C------CTGS--C
(omega_conotoxin)_SNX-194             ------------------C-----KGKGAKC-----S-RLXYD---C------CTGS--C
(omega_conotoxin)_SNX-279             ------------------C-----KGKGAKC-----S-RLXYD---C------CTGS--C
(omega_conotoxin)_SNX-257             ------------------C-----KGKGAKC-----S-RLMFD---C------CTGS--C
(omega_conotoxin)_SNX-191             ------------------C-----AGKGAKC-----S-RLMYD---C------CTGS--C
(omega_conotoxin)_SNX-195             ------------------C-----KGKGAKC-----S-RLMYD---C------CTGS--C
(omega_conotoxin)_SNX-190             ------------------C-----KGAGAKC-----S-RLMYD---C------CTGS--C
(omega_conotoxin)_SNX-198             ------------------C-----KGKGAKC-----S-RLMYD---C------CTGS--C
(omega_conotoxin)_SNX-199             ------------------C-----KGKGAKC-----S-ALMYD---C------CTGS--C
(omega_conotoxin)_SNX-200             ------------------C-----KGKGAAC-----S-RLMYD---C------CTGS--C
(omega_conotoxin)_SNX-259             ------------------C-----KGKGAKC-----S-RLMXD---C------CTGS--C
(omega_conotoxin)_SNX-288             ------------------C-----KGKGAKC-----S-RAMYD---C------CTGS--C
(omega_conotoxin)_SNX-308             ------------------C-----KGKGAKC-----S-RLMYA---C------CTGS--C
(omega_conotoxin)_MVIIA[R10K]         ------------------C-----KGKGAKC-----S-KLMYD---C------CTGS--C
(omega_conotoxin)_MVIIA               ------------------C-----KGKGAKC-----S-RLMYD---C------CTGS--C
(omega_conotoxin)_SNX-220             -----------------XC-----KGKGAKC-----S-RLMYD---C------CTGS--C
(omega_conotoxin)_MVIIA_With_C-T      ------------------C-----KGKGAKC-----S-RLMYD---C------CTGS--C
                                                                                                  

(gamma_conotoxin)_PnVIIA              ------DQTY------C------ELYAFPS
(delta_conotoxin)_Evia_Loop_2_An      ------------------------------
(alpha_conotoxin)_SII                 ----------------C------S------
(alpha_conotoxin)_SI                  ----------------X-------------
(mu_conotoxin)_SxIIIA                 ----------------C------AX-----
(mu_conotoxin)_SxIIIB                 ----------------C------AX-----
(mu_conotoxin)_CIIIA                  ----------------C------X------
(mu_conotoxin)_KIIIA[Del1,S3/S4A      ----------------C------N------
(mu_conotoxin)_SIIIB                  ----------------C------X------
(mu_conotoxin)_CnIIIC                 ----------------C------X------
(mu_conotoxin)_SIIIA                  ----------------C------X------
(mu_conotoxin)_KIIIA[C2A,C15A]        ----------------C------N------
(mu_conotoxin)_KIIIA[C4A,C16A]        ----------------C------AN-----
(mu_conotoxin)_KIIIA[C1A,C9A]         ----------------C------N------
(mu_conotoxin)_SmIIIA                 ----------------C-------------
(mu_conotoxin)_KIIIA                  ----------------C------N------
(mu_conotoxin)_MIIIA                  ----------------C------X------
(mu_conotoxin)_CnIIIA                 ----------------C------X------
(kappa_conotoxin)_PlXIVA              ------KYPF------C------HCRX---
(gamma_conotoxin)_DeVIIA              ------LIYR------C------SX-----
(alpha_conotoxin)_RVIIIA              ------MKSG------C------ACICTYY
(omega_conotoxin)_SO4                 ------SPYSKI----C------MNYPKN-
(omega_conotoxin)_SO5                 ------AYFGKK----C------IDYPSN-
(omega_conotoxin)_PuIIA               ----HKTIHA------C------A------
(mu_conotoxin)_CnIIIB                 ----------------C------RQQ----
(gamma_conotoxin)_TxVIIA              ------VRSY------C------TLFX---
(alpha_conotoxin)_PIIIE               ----------------C------QRX----
(mu_conotoxin)_TIIIA                  ------RPQH------C------CX-----
(alpha_conotoxin)_SrIA                -------PEL------C------GX-----
(omega_conotoxin)_TxO2                -------IFV------C------L------
(omega_conotoxin)_TxO3                -------IFV------C------F------
(chi_conotoxin)_CMrX                  ------YP--------C-------------
(alpha_conotoxin)_Qc1.2               ----------------C------X------
(mu_conotoxin)_LtVIC                  ----------------V-------------
(kappa_conotoxin)_RIIIK               ----------------C------TX-----
(mu_conotoxin)_PIIIA                  ----------------C------X------
(kappa_conotoxin)_MIVA                ----------------C------PPKRKPX
(kappa_conotoxin)_SIVA                ----------------C------X------
(omega_conotoxin)_SVIA                ----------------X-------------
(omega_conotoxin)_SVIA_mutant_1       ------------------------------
(chi_conotoxin)_Cyclic_MrIA           ------------------------------
(chi_conotoxin)_MrIA                  ------------------------------
(chi_conotoxin)_CMrVIA_amidated       ----------------X-------------
(chi_conotoxin)_MrIB_C-term_amid      ----------------X-------------
(chi_conotoxin)_MrIB                  ------------------------------
(chi_conotoxin)_CMrVIA                ------------------------------
(chi_conotoxin)_CMrVIA_[K6P]          ------------------------------
(chi_conotoxin)_CMrVIA_[K6P]_ami      ----------------X-------------
(alpha_conotoxin)_Lp1.1               -------QEL------C------X------
(delta_conotoxin)_CnVIA               ------LFFV------C------LTFS---
(delta_conotoxin)_NgVIA               ------FSLF------C------ISFE---
(delta_conotoxin)_MVID                ------LSFV------C------ISFDF--
(delta_conotoxin)_MVIC                ------LSFV------C------ISFDF--
(delta_conotoxin)_EVIB                ------LPAV------C------VGX----
(delta_conotoxin)_PVIA                ------LPGV------C------FGX----
(delta_conotoxin)_EVIA                -------VGV------C------ADLX---
(omega_conotoxin)_PnVIA               -------VFV------C------TPQ----
(alpha_conotoxin)_PIB                 ----------------C------X------
(omega_conotoxin)_PnVIB               -------FFA------C------A------
(omega_conotoxin)_TxO4                -------FFA------C------A------
(delta_conotoxin)_BVIA                -------FFA------C------F------
(delta_conotoxin)_CVIE                -------LVW------C------T------
(delta_conotoxin)_AVIA                -------IVW------C------T------
(delta_conotoxin)_MVIB                -------ILW------C------ITFVDSX
(delta_conotoxin)_MVIA                -------FLW------C------ITFVDSX
(delta_conotoxin)_SmVIA               -------FLW------C------ITFID--
(delta_conotoxin)_SVIE                -------FLW------C------ITFID--
(omega_conotoxin)_PuIA                -------AII------C------VS-----
(alpha_conotoxin)_MII_[N5Ada]         -------SNL------C-------------
(alpha_conotoxin)_MII_[E11A]          -------SNL------C------X------
(alpha_conotoxin)_MII                 -------SNL------C------X------
(alpha_conotoxin)_MII-7               -------SNL------C------GAGGAAG
(alpha_conotoxin)_MII-6               -------SNL------C------G-GAAGG
(alpha_conotoxin)_Ada-MII             -------SNL------C-------------
(alpha_conotoxin)_ImII                ----------------C------N------
(alpha_conotoxin)_ImII-iso            ----------------C------N------
(alpha_conotoxin)_ImII_[W10Y]         ----------------C------N------
(alpha_conotoxin)_Epi_[sTy15>Y]       -------PDY------C------X------
(alpha_conotoxin)_EpI                 -------PDY------C------X------
(alpha_conotoxin)_Vc1.1[N9D]          -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[N9L]          -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[N9I]          -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[N9K]          -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[N9G]          -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[S4K,N9A]      -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[N9A]          -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[I15D]         -------PED------C------X------
(alpha_conotoxin)_Vc1.1[I15K]         -------PEK------C------X------
(alpha_conotoxin)_Vc1.1[I15A]         -------PEA------C------X------
(alpha_conotoxin)_Vc1.1[E14K]         -------PKI------C------X------
(alpha_conotoxin)_Vc1.1[E14A]         -------PAI------C------X------
(alpha_conotoxin)_Vc1.1[E14D]         -------PDI------C------X------
(alpha_conotoxin)_Vc1.1[S4D]          -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[S4K]          -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[S4R]          -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[S4A]          -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[D5K]          -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[D5A]          -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[P13D]         -------DEI------C------X------
(alpha_conotoxin)_Vc1.1[P13K]         -------KEI------C------X------
(alpha_conotoxin)_Vc1.1[P13A]         -------AEI------C------X------
(alpha_conotoxin)_Vc1.1[D11K]         -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[D11A]         -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[P6D]          -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[P6K]          -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[P6A]          -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[R7D]          -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[R7A]          -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[R7K]          -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[Y10D]         -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[Y10K]         -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[Y10A]         -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[G1D]          -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[G1K]          -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[G1A]          -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[H12D]         -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[H12A]         -------PEI------C------X------
(alpha_conotoxin)_Vc1.1               -------PEI------C------X------
(alpha_conotoxin)_Vc1.1[H12K]         -------PEI------C------X------
(alpha_conotoxin)_Reg1e               ----------------C------X------
(alpha_conotoxin)_RgIA                ----------------C------R------
(alpha_conotoxin)_Reg1b/Reg1c         ----------------C------X------
(alpha_conotoxin)_Reg1d               ----------------C------X------
(alpha_conotoxin)_ImI_[P6A]           ----------------C------N------
(alpha_conotoxin)_ImI_[P6K]           ----------------C------N------
(alpha_conotoxin)_ImI_[P6K]_deam      ----------------C-------------
(alpha_conotoxin)_ImI_[R11E]          ----------------C------X------
(alpha_conotoxin)_ImI_[D5N]           ----------------C------X------
(alpha_conotoxin)_ImI_[R7L]           ----------------C------X------
(alpha_conotoxin)_ImI                 ----------------C------X------
(alpha_conotoxin)_ImI_[C2U,C8U]       ----------------C------X------
(alpha_conotoxin)_ImI_[C2U,C3U,C      ----------------C------X------
(alpha_conotoxin)_ImI_deamidated      ----------------C-------------
(alpha_conotoxin)_ArIB_[N6R,A8P]      -------PHV------C------RRR----
(alpha_conotoxin)_ArIB_[V1            -------PHD------C------RRR----
(alpha_conotoxin)_ArIB_[V11L]         -------PHV------C------RRR----
(alpha_conotoxin)_ArIB_[V2            -------PHA------C------RRR----
(alpha_conotoxin)_GID*[V18A]          -------PHA------C-------------
(alpha_conotoxin)_GID*[O16A]          -------AHV------C-------------
(alpha_conotoxin)_GID*[P9A]           -------PHV------C-------------
(alpha_conotoxin)_GID*[S7A]           -------PHV------C-------------
(alpha_conotoxin)_GID*[H17A]          -------PAV------C-------------
(alpha_conotoxin)_GID*[N15A]          -------PHV------C-------------
(alpha_conotoxin)_GID*[N8A]           -------PHV------C-------------
(alpha_conotoxin)_GID*[V13A]          -------PHV------C-------------
(alpha_conotoxin)_GID*[N14A]          -------PHV------C-------------
(alpha_conotoxin)_GID[R12A]           -------PHV------C-------------
(alpha_conotoxin)_GID[Gla4Ala]        -------PHV------C-------------
(alpha_conotoxin)_GID[Del1-3,Gla      -------PHV------C-------------
(alpha_conotoxin)_GID[Del4]           -------PHV------C-------------
(alpha_conotoxin)_GID*[D3A]           -------PHV------C-------------
(alpha_conotoxin)_GID*[Del1-2,D3      -------PHV------C-------------
(alpha_conotoxin)_GID*[Del1-3]        -------PHV------C-------------
(alpha_conotoxin)_GID*-NH2            -------PHV------C------X------
(alpha_conotoxin)_GID                 -------PHV------C-------------
(alpha_conotoxin)_GID*                -------PHV------C-------------
(alpha_conotoxin)_GID*[O16P]          -------PHV------C-------------
(alpha_conotoxin)_GID*[Del1,R2A]      -------PHV------C-------------
(alpha_conotoxin)_GID*[R2A]           -------PHV------C-------------
(alpha_conotoxin)_ArIA                -------PHV------C------RRR----
(alpha_conotoxin)_GID*[I1A]           -------PHV------C-------------
(alpha_conotoxin)_ArIB                -------PHV------C------RRR----
(alpha_conotoxin)_PeIA                -------PEL------C------X------
(alpha_conotoxin)_BuIA                ----------------C------X------
(alpha_conotoxin)_OmIA                -------PHI------C------GX-----
(alpha_conotoxin)_RegIIA              -------PHI------C------X------
(alpha_conotoxin)_GIC                 -------QHI------C------X------
(alpha_conotoxin)_AnIB                -------QDY------C------X------
(alpha_conotoxin)_AnIA                -------QDY------C------X------
(alpha_conotoxin)_AuIB                -------PD-------C------X------
(alpha_conotoxin)_AuIC                -------SGY------C------X------
(alpha_conotoxin)_AuIA                -------SDY------C------X------
(alpha_conotoxin)_TxIA                -------PDL------C------X------
(alpha_conotoxin)_PnIA_[A10L,D14      -------PKY------C------X------
(alpha_conotoxin)_PnIA                -------PDY------C------X------
(alpha_conotoxin)_Pni1                -------PDY------C------X------
(alpha_conotoxin)_PnIB                -------PDY------C------X------
(alpha_conotoxin)_Reg1f               ---------I------C------X------
(alpha_conotoxin)_EI                  -------PQI------C------X------
(alpha_conotoxin)_PIA                 -------PQI------C------X------
(alpha_conotoxin)_VxXXC               TCAYNWRRGIYCS---C-------------
(alpha_conotoxin)_VxXXB               TCVYHWRRGHG-----C------SCPG---
(alpha_conotoxin)_VxXXA               CVYHRGRGHG------C------SC-----
(mu_conotoxin)_conotoxin-GS           ---GRGNPQK------C------IGAHEDV
(kappa_conotoxin)_PIVF                ----------------CKKSGKX-------
(kappa_conotoxin)_PIVE                ----------------C------KNYGKX-
(alpha_conotoxin)_GI_[S12>Benzoy      ----------------C-------------
(alpha_conotoxin)_GI                  ----------------C------X------
(alpha_conotoxin)_GIA                 ----------------C------GK-----
(alpha_conotoxin)_GI_[N4>Benzoyl      ----------------C-------------
(alpha_conotoxin)_SIA                 ----------------C------X------
(alpha_conotoxin)_CnIA                ----------------C------X------
(alpha_conotoxin)_MI                  ----------------C------X------
(alpha_conotoxin)_Ac1.1a              ----------------C------X------
(alpha_conotoxin)_GII                 ----------------C------X------
(kappa_conotoxin)_BtX                 -------WGG------C-----GHPCRHPX
(delta_conotoxin)_GmVIA               -------VLF------C------V------
(omega_conotoxin)_TxVII               -------LGV------C------MW-----
(omega_conotoxin)_TxO1                ------ILLF------C------A------
(delta_conotoxin)_Am2766              -------AFI------C------IEX----
(alpha_conotoxin)_PrIIIE              ------RRKY------C------CX-----
(omega_conotoxin)_TxO6                ------TLFF------C------A------
(omega_conotoxin)_TxO5                ------VVFW------C------L------
(mu_conotoxin)_MrVIA                  ------GPFV------C------V------
(mu_conotoxin)_MrVIB                  ------GPFV------C------V------
(alpha_conotoxin)_PIIIF               ------YNAL------C------CRKX---
(delta_conotoxin)_TxVIA               ------IVLV------C------T------
(delta_conotoxin)_TxVIB               ------IVFV------C------T------
(mu_conotoxin)_PnIVB                  --------------G-C-------------
(mu_conotoxin)_PnIVA                  --------------G-C-------------
(alpha_conotoxin)_PIVA                ----KDRPSY------C------GQX----
(alpha_conotoxin)_PIVA_[Hyp7P,Hy      ----KDRXSY------C------GQX----
(alpha_conotoxin)_EIVA                ---KVGRPPY------C------DRPSGGX
(alpha_conotoxin)_EIVB                ---------TVGRPPYC------DRPSGGX
(alpha_conotoxin)_OIVB                -------NKT------C------GX-----
(alpha_conotoxin)_OIVA                -------KNT------C------X------
(alpha_conotoxin)_PeIVB               -------TGK------C-------------
(alpha_conotoxin)_PeIVA               -------TGK------C-------------
(kappa_conotoxin)_PVIIA               -----NRFNK------C------VX-----
(omega_conotoxin)_TVIA                ----NPYSRK------C-------------
(omega_conotoxin)_GVIA_[O10>K]        ----NNYTKR------C------YN-----
(omega_conotoxin)_GVIA                NPYTKR----------C------YX-----
(gamma_conotoxin)_AsVIIA              ------KPGGPLFDFDC-------------
(omega_conotoxin)_GVIIA               ----------LLYSNKC------RRY----
(omega_conotoxin)_GVIIB               ----------LSYSNKC------RRY----
(mu_conotoxin)_GIIIA_[R13A]           -KDAQCKPQR------C------CAX----
(mu_conotoxin)_GIIIA                  -KDRQCKPQR------C------CAX----
(mu_conotoxin)_GIIIB                  -KDRRCKPMK------C------CAX----
(mu_conotoxin)_GIIIC                  -KDRRCKPLK------C------CAX----
(omega_conotoxin)_RVIA                ----------KSYNKKC------G------
(alpha_conotoxin)_LtXIVA              ------KPSCTN----C------X------
(mu_conotoxin)_LtVd                   ----------------C------NP-----
(omega_conotoxin)_SO3                 ------RSGK------C------X------
(omega_conotoxin)_MVIID               ------NRGR------C------X------
(omega_conotoxin)_MVIIB               ------NRGK------C------N------
(omega_conotoxin)_CVIA                ------RSGR------C------N------
(omega_conotoxin)_CVID                ----SGTVGR------C------X------
(omega_conotoxin)_CnVIIA              ----SSSKGR------C------X------
(omega_conotoxin)_SVIB                -----GRSGK------C------X------
(omega_conotoxin)_SNX-202             -----GRSGK------C-------------
(omega_conotoxin)_MVIIC               -----GRRGK------C------X------
(omega_conotoxin)_MVIIC_analog        -----GRRGR------C------X------
(omega_conotoxin)_CVIB                ------RSGR------C------N------
(omega_conotoxin)_SNX-201             ------RSGK------C-------------
(omega_conotoxin)_CVIC                -----SRRGK------C------X------
(omega_conotoxin)_SNX-273             ------RSGK------C-------------
(omega_conotoxin)_SNX-194             ------RSGK------C-------------
(omega_conotoxin)_SNX-279             ------RSGK------C-------------
(omega_conotoxin)_SNX-257             ------RSGK------C-------------
(omega_conotoxin)_SNX-191             ------RSGK------C-------------
(omega_conotoxin)_SNX-195             ------RSGA------C-------------
(omega_conotoxin)_SNX-190             ------RSGK------C-------------
(omega_conotoxin)_SNX-198             ------ASGK------C-------------
(omega_conotoxin)_SNX-199             ------RSGK------C-------------
(omega_conotoxin)_SNX-200             ------RSGK------C-------------
(omega_conotoxin)_SNX-259             ------RSGK------C-------------
(omega_conotoxin)_SNX-288             ------RSGK------C-------------
(omega_conotoxin)_SNX-308             ------RSGK------C-------------
(omega_conotoxin)_MVIIA[R10K]         ------RSGK------C------X------
(omega_conotoxin)_MVIIA               ------RSGK------C------X------
(omega_conotoxin)_SNX-220             ------RSGK------C-------------
(omega_conotoxin)_MVIIA_With_C-T      ------RSGK------C------G------
                                                                    
